name: Android CI

on:
  pull_request:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Remove Android 31 (S)
      run: $ANDROID_HOME/tools/bin/sdkmanager --uninstall "platforms;android-31"

    - name: Build with Gradle
      run: ./gradlew assemblePlayProdRelease

    - name: Sign the crap
      run: |
        cd app/build/outputs/apk/playProd/release/
        keytool -dname "CN=commonName, OU=organizationUnit, O=organizationName, L=localityName, S=stateName, C=country" -keypass yourmother -storepass yourmother -genkey -v -keystore example.keystore -alias SomeAlias -keyalg RSA -keysize 4096
        jarsigner -keypass yourmother -storepass yourmother -verbose -keystore example.keystore Signal-Android-play-prod-armeabi-v7a-release-unsigned-6.8.3.apk SomeAlias

    - run: ls -alR .

    - name: Upload stuff
      uses: actions/upload-artifact@v3
      with:
        path: 'app/build/outputs/apk/playProd/release/Signal-Android-play-prod-armeabi-v7a-release-unsigned-6.8.3.apk'
